# Generated by Django 5.2.1 on 2025-05-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_return_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='repeat_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
