# Generated by Django 5.2.1 on 2025-05-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='timezone',
            field=models.CharField(choices=[('Pacific/Auckland', 'Mainland NZ'), ('Pacific/Chatham', 'Chatham Islands'), ('Australia/Melbourne', 'Melbourne')], default='Pacific/Auckland', max_length=30),
        ),
    ]
