# Generated by Django 5.2.1 on 2025-05-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_flight_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='is_return_flight',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='repeat_weekly',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='timezone',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_timezone',
            field=models.CharField(choices=[('Pacific/Auckland', 'Mainland NZ'), ('Pacific/Chatham', 'Chatham Islands'), ('Australia/Melbourne', 'Melbourne')], default='Pacific/Auckland', max_length=30),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_timezone',
            field=models.CharField(choices=[('Pacific/Auckland', 'Mainland NZ'), ('Pacific/Chatham', 'Chatham Islands'), ('Australia/Melbourne', 'Melbourne')], default='Pacific/Auckland', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
