# Generated by Django 5.2.1 on 2025-05-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_flight_is_return_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
